openapi: 3.0.1
info:
  title: Wista-S3
  description: 将 Wistia 上的视频上传至 S3。
  version: V1
servers:
  - url: /
tags: []
paths:
  /refresh/media:
    post:
      tags: []
      summary: 从S3刷新所有 uploaded video 到 local DB
      description: <p>从S3刷新所有 uploaded video 到 local DB</p>
      responses:
        500:
          description: API报错
          content: { }
        200:
          description: PDF文件内容
          content: { }
  /media:
    get:
      tags: []
      summary: 获取所有 uploaded 视频信息
      description: <p>获取所有 uploaded 视频信息</p>
      parameters:
        - name: hash
          in: query
          description: 视频 HashId
          schema: 
            type:  string
      responses:
        500:
          description: API报错
          content: { }
        200:
          description: PDF文件内容
          content: { }

  /tasks/{id}:
    get:
      tags: []
      summary: 获取任务状态
      description: <p>获取任务状态</p>
      parameters:
        - name: id
          in: path
          description: 任务ID
          required: true
          schema:
            type: string
      responses:
        500:
          description: API报错
          content: { }
        200:
          description: PDF文件内容
          content: { }
  
  /move/{hash}:
    post:
      tags: []
      summary: 迁移Video到S3
      description: <p>迁移Video到S3</p>
      operationId: "single-move"
      parameters:
        - name: hash
          in: path
          description: Wistia Video HashId
          required: true
          schema:
            type: string
      responses:
        500:
          description: API报错
          content: {}
        200:
          description: PDF文件内容
          content: {}
    
  /move:
    post:
      tags: []
      summary: 批量迁移Video到S3
      description: <p>批量迁移Video到S3</p>
      operationId: "multiple-move"
      requestBody: 
        required: true
        content: 
          application/json: 
            schema: 
              type: object
              properties: 
                media:
                  type: array
                  items: 
                     type: string
                     description: 视频HashId
      responses:
        500:
          description: API报错
          content: {}
        200:
          description: PDF文件内容
          content: {}
components: {}
