version: "3"
services:
  email2db:
    image: "mmhk/wistia-s3"
    restart: always
    environment:
      - S3_KEY=$S3_KEY
      - S3_SECRET=$S3_SECRET
      - S3_REGION=ap-southeast-1
      - S3_BUCKET=s3.test.mixmedia.com
      - S3_PREFIX=wistia-backup
      - S3_CLOUDFRONT_DOMAIN=$S3_CLOUDFRONT_DOMAIN
      - WISTIA_API_KEY=$WISTIA_API_KEY
      - WISTIA_WORKER_LIMIT=3
      - TEMPLATE_DIR_PATH=/app/web/dist
      - LOG_LEVEL=INFO
      - TZ=Asia/Hong_Kong
      - LISTEN=0.0.0.0:3031
      - WEBROOT=/app/webroot
      - DB_FILE_PATH=/app/wista-s3.db
    ports:
      - "3031:3031"
