name: wistia-s3-player

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Get current version
        id: get_version
        run: echo "CURRENT_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Check if version changed
        id: version_check
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          current_version=$CURRENT_VERSION
          if [ "$latest_tag" == "v$current_version" ]; then
            echo "::set-output name=version_changed::false"
          else
            echo "::set-output name=version_changed::true"
          fi

      - name: Publish to npm
        if: steps.version_check.outputs.version_changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create and push tag
          if: steps.version_check.outputs.version_changed == 'true'
          run: |
            git tag -a "v$CURRENT_VERSION" -m "Release version $CURRENT_VERSION"
            git push origin "v$CURRENT_VERSION"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
